# Generated by Django 2.0.6 on 2020-04-09 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
