# Generated by Django 2.0.6 on 2020-04-09 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_registerapp', '0002_auto_20200409_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=100, verbose_name='标号')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='正文')),
                ('status', models.CharField(choices=[('d', '草稿'), ('p', '发表')], default='p', max_length=1, verbose_name='状态')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'article',
                'verbose_name_plural': '文章列表',
                'verbose_name': '文章',
                'get_latest_by': 'created_time',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('username', models.CharField(max_length=50)),
                ('userimg', models.CharField(max_length=70)),
                ('nickname', models.CharField(default='匿名', max_length=50)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('article', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comment',
                'verbose_name_plural': '评论列表',
                'ordering': ['-createtime'],
                'verbose_name': '评论',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='类别名称')),
            ],
            options={
                'db_table': 'category',
                'verbose_name_plural': '分类列表',
                'ordering': ['name'],
                'verbose_name': '类别名称',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='标签名')),
            ],
            options={
                'db_table': 'tag',
                'verbose_name_plural': '标签列表',
                'ordering': ['name'],
                'verbose_name': '标签名称',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_registerapp.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='login_registerapp.Tag', verbose_name='标签集合'),
        ),
    ]
