# Generated by Django 2.0.6 on 2020-04-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registerapp', '0003_auto_20200409_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='writer',
            field=models.CharField(default='', max_length=50),
        ),
    ]
